id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
# ──────────────────────────────────────────────────────────────────────────────
# ACL NAMING CONVENTIONS:
#   id:           access_<model_underscore>_<group_suffix>
#   name:         <model.name>.<group_suffix>   (human-readable)
#   model_id:id:  model_<model_underscore>       (auto-generated by Odoo)
#   group_id:id:  <module_name>.<group_xml_id>   or base.group_user, etc.
#   perm_*:       1 = allowed, 0 = denied
#
# COMMON GROUPS:
#   base.group_user            → Internal User (all logged-in users)
#   base.group_system          → Technical / Administrator
#   base.group_portal          → Portal User
#   base.group_public          → Public (unauthenticated)
#   <module>.group_<name>_user    → Custom user group
#   <module>.group_<name>_manager → Custom manager group
# ──────────────────────────────────────────────────────────────────────────────
#
# TEMPLATE — replace {{ placeholders }} and add one line per model × group:
#
# Model: {{ model.name }} ({{ model_underscore }})
access_{{ model_underscore }}_user,{{ model.name }}.user,model_{{ model_underscore }},{{ module_name }}.group_{{ module_name }}_user,1,1,1,0
access_{{ model_underscore }}_manager,{{ model.name }}.manager,model_{{ model_underscore }},{{ module_name }}.group_{{ module_name }}_manager,1,1,1,1
#
# Wizard: {{ module_name }}.{{ wizard_suffix }}.wizard
# access_{{ module_name }}_{{ wizard_suffix }}_wizard_user,{{ module_name }}.{{ wizard_suffix }}.wizard.user,model_{{ module_name }}_{{ wizard_suffix }}_wizard,{{ module_name }}.group_{{ module_name }}_user,1,1,1,1
#
# If no custom groups exist, grant to all internal users:
# access_{{ model_underscore }}_all,{{ model.name }}.all,model_{{ model_underscore }},base.group_user,1,1,1,0
