<?xml version="1.0" encoding="utf-8"?>
<!-- Customer Portal Templates — Odoo 16.0–19.0 -->
<!-- Replace all {{ placeholders }} with actual values. -->
<!-- Must be loaded in the 'data' section of __manifest__.py -->
<odoo>

    <!-- 1. The List View (List of records in the portal) -->
    <template id="{{ module_name }}.portal_my_{{ record_plural }}" name="My {{ Record Plural }}">
        <!-- Wraps the view in the standard portal layout -->
        <t t-call="portal.portal_layout">
            
            <!-- Breadcrumbs definition -->
            <t t-set="breadcrumbs_searchbar" t-value="True"/>
            <t t-call="portal.portal_searchbar">
                <t t-set="title">{{ Record Plural }}</t>
            </t>
            
            <!-- Handle Empty State -->
            <t t-if="not {{ record_plural }}">
                <p class="alert alert-warning">There are currently no {{ Record Plural }} for your account.</p>
            </t>
            
            <!-- Handle Data State -->
            <t t-if="{{ record_plural }}" t-call="portal.portal_table">
                <thead>
                    <tr class="active">
                        <th>Reference</th>
                        <th>Date</th>
                        <th class="text-end">Status</th>
                    </tr>
                </thead>
                <t t-foreach="{{ record_plural }}" t-as="record">
                    <tr>
                        <td>
                            <!-- URL usually generated by the controller or model's get_portal_url() -->
                            <a t-attf-href="/my/{{ url_path }}/#{record.id}?{{ keep_query() }}">
                                <t t-esc="record.name"/>
                            </a>
                        </td>
                        <td><span t-field="record.create_date" t-options="{'widget': 'date'}"/></td>
                        <td class="text-end">
                            <span class="badge rounded-pill text-bg-info">
                                <i class="fa fa-fw fa-clock-o" aria-label="Status" title="Status" role="img"/>
                                <span t-field="record.state"/>
                            </span>
                        </td>
                    </tr>
                </t>
            </t>
        </t>
    </template>

    <!-- 2. The Form/Detail View (Single record detail) -->
    <template id="{{ module_name }}.portal_my_{{ record_singular }}" name="My {{ Record Singular }}">
        <t t-call="portal.portal_layout">
            <t t-set="o_portal_fullwidth_alert" groups="project.group_project_user">
                <!-- Example of an alert shown only to internal users viewing the portal -->
                <t t-call="portal.portal_back_in_edit_mode">
                    <t t-set="backend_url" t-value="'/web#model={{ model.name }}&amp;id=%s&amp;view_type=form' % (record.id)"/>
                </t>
            </t>

            <!-- Wrap in portal record layout -->
            <t t-call="portal.portal_record_layout">
                <t t-set="card_header">
                    <div class="row no-gutters">
                        <div class="col-12">
                            <h5 class="d-flex mb-1 mb-md-0 row">
                                <div class="col-9">
                                    <t t-esc="record.name"/>
                                </div>
                                <div class="col-3 text-end">
                                    <small class="text-end">Status:</small>
                                    <span t-field="record.state" class="badge rounded-pill text-bg-info"/>
                                </div>
                            </h5>
                        </div>
                    </div>
                </t>
                <t t-set="card_body">
                    <div class="row mb-4">
                        <div class="col-12 col-md-6 mb-2 mb-md-0">
                            <strong>Date:</strong> <span t-field="record.create_date" t-options='{"widget": "date"}'/>
                        </div>
                        <div class="col-12 col-md-6">
                            <strong>Company:</strong> <span t-field="record.company_id.name"/>
                        </div>
                    </div>
                    
                    <!-- Example Table of lines inside the record -->
                    <!--
                    <t t-if="record.line_ids">
                        <table class="table table-sm">
                            <thead>
                                <tr><th>Description</th></tr>
                            </thead>
                            <tbody>
                                <t t-foreach="record.line_ids" t-as="line">
                                    <tr><td t-esc="line.name"/></tr>
                                </t>
                            </tbody>
                        </table>
                    </t>
                    -->
                </t>
            </t>
            
            <!-- Chatter Integration -->
            <div id="{{ record_singular }}_communication" class="mt-4">
                <h2>History</h2>
                <t t-call="portal.message_thread">
                    <t t-set="object" t-value="record"/>
                </t>
            </div>

        </t>
    </template>

</odoo>
